### ISSUE TITLE
Add oEmbed type to StartBox Options API

### ISSUE THREAD

**Issue by williamsba** [WebDevStudios/StartBox#32]

**Comment by brichards** [comment]
Brad, could you elaborate on this request? What are you looking for exactly?

**Comment by jtsternberg** [comment]
He's looking for us to implement a new field type like the one I added to CMB. https://github.com/jaredatch/Custom-Metaboxes-and-Fields-for-WordPress/commit/d40d7bd45c1effa06b281e5f72bb11772ff0d6ce

**Comment by brichards** [comment]
Ah, well I think such an option type is unnecessary then, because the option itself only appears on the Theme Options page. To achieve oembed support on front-end output (presumably the reason an option would be added), the option's value can just be run through apply_filters( 'the_content', $option_value ); ... right? In which case, using a normal text or textarea option would suffice.
