### ISSUE TITLE
Upgrade to 2.7.1 Breaks Slideshows and Removes Widgets

### ISSUE THREAD

**Issue by karks88** [WebDevStudios/StartBox#44]
Happened with an automatic upgrade from 2.6 on my site, http://www.karks.com/

The slideshow shows up on the page, but is blank (links still work).  In the admin, all images are blank.

For widgets, they were all moved to an inactive area, but all data was saved.

I went back to 2.6 to restore the slideshows.  Hope this helps!

**Comment by brichards** [comment]
I believe we've identified the issue with the deactivated widgets in issue #47. The issue with the broken slideshow images, I believe, is due to how StartBox is now writing/reading the image files within the media library. I still think your issue is an exception, because they do work in all the installs I've tested work correctly. I have seen a few other instances where slideshows are broken, but I'm having trouble connecting the issues to a common thread.

I recommend, in any case, to move away from using the built-in slideshows feature because there are many plugins that are better and more light-weight than our current setup. I recommend this whether you're running 2.7+, or 2.6 and lower. Soliloquy is a good solution (http://soliloquywp.com/) and Chris Lema reviews a few other good ones here:  http://chrislema.com/comparing-premium-sliders-for-wordpress-by-performance/.

I'm going to close this ticket out and instead focus on #47 for handling the sidebar issues.
