### ISSUE TITLE
Widget sidebar woes

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/StartBox#47]
More a note than an actual issue. I bet https://github.com/WebDevStudios/StartBox/commit/14497475529658fe0fe5f12f3315dc90710c4d1f probably broke the widget sidebars for people. Widget IDs/names/whatevs were renamed. Something to keep in mind if others bring it up.

**Comment by brichards** [comment]
Yep, that's why I put this little bit in the upgrade routine in the next commit: https://github.com/WebDevStudios/StartBox/blob/6237f32133434c5855b3598aae3ea095933e4058/includes/functions/startbox.php#L438-L448

**Comment by brichards** [comment]
Ah ha! The root issue is that any child themes running their own version of sidebar.php will almost definitely have kept the original `sb_do_sidebar( 'primary', 'primary_widget_area' );` and `sb_do_sidebar( 'secondary', 'secondary_widget_area');`.

Because the custom sidebar.php exists, it override StartBox's updated sidebar.php which contains the new `sb_do_sidebar( 'primary', 'primary' );` and `sb_do_sidebar( 'secondary', 'secondary' );`

The upgrade routine specifically unregisters the widgets from 'primary_widget_area' and 'secondary_widget_area', assigning them instead to 'primary' and 'secondary', which aren't available in this theme, thus resulting in their deactivation.
