### ISSUE TITLE
Upgrade Killed Site

### ISSUE THREAD

**Issue by mdusing** [WebDevStudios/StartBox#59]
I upgraded through the Wordpress dashboard and the upgrade entirely killed my site.

Error: 
Fatal error: Call to undefined function wp_get_image_editor() in /home/dusing/public_html/michael/wp-content/themes/startbox/includes/functions/images.php on line 188

Then I replaced the startbox folder with an older version and wp wouldn't let me in to the backend at all. Backing up files before trying your solution of deleting the startbox folder entirely to get in.

**Comment by brichards** [comment]
Talked through this via Twitter, the issue was that WP had not yet been updated to 3.5 (released December 11, or 217 days ago, tisk tisk Michael!) prior to updating to SB 2.7.x.

The solution (on our end) is to not show an available update unless the site is running WP is 3.5 or greater. I've updated the server-side update listener to ensure this is the case.
